### ISSUE TITLE
Explode Deprecation Warning

### ISSUE THREAD

**Issue by wuifdesign** [mitydigital/statamic-iconamic#11]
### Bug description

getting a warning when using this addon:

```
explode(): Passing null to parameter #2 ($string) of type string is deprecated in vendor/mitydigital/iconamic/src/Support/Iconamic.php on line 99
```

### Steps to reproduce

install the addon

### Environment and versions

```yaml
Environment
Laravel Version: 11.44.1
PHP Version: 8.2.28
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: 127.0.0.1:8000
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 6
Sites: 2 (English, German)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.50.0 PRO

Statamic Addons
appswithlove/statamic-one-click-content-translation: 5.2.3
jacksleight/statamic-distill: 0.8.2
mitydigital/iconamic: 2.2.2
ndx/statamic-bard-color-picker: 2.0.1
teamnovu/statamic-images-missing-alt: 1.0.5
webographen/statamic-widget-continue-editing: 1.3.2
```
