### ISSUE TITLE
Folder in icons folder ending in .svg causes error

### ISSUE THREAD

**Issue by Jade-GG** [mitydigital/statamic-iconamic#3]
### Bug description

When you create a folder inside of the `resources/icons` folder that ends in `.svg`, iconamic will try to read the folder as if it's a file and throw an error.

### Steps to reproduce

- Create a new folder in the `resources/icons` folder (or whichever one you have set up in your configuration)
- Name it something like `test.svg`
- Open any statamic page with the iconamic addon
- Observe the crash

### Environment and versions

```yaml
Laravel Version: 9.44.0
PHP Version: 8.1.14
Composer Version: 2.2.9
Statamic version: 3.3.62 PRO
mitydigital/iconamic: 1.1.1
```
