### ISSUE TITLE
Dropdown is displayed below the other sections.

### ISSUE THREAD

**Issue by Smilesharks** [mitydigital/statamic-iconamic#4]
### Bug description

The problem is that the dropdown options are displayed underneath subsequent fields and sections, and the bug started when we upgraded from Statamic 3 to version 4.
The error persists both when adding the Iconamic field to an existent set or creating a new one.

Comparing a default select with an Iconamic field, I found that the difference is that the "ul" container for the options is added at the end of the code, while in the case of Iconamic it is added below the search field.

Thanks in advance.

### Steps to reproduce

Create Field
Fieldtypes > Iconamic
Set path to folder
Add fieldset to a template
Add set to a page that uses that template

### Environment and versions

```yaml
Laravel Version: 9.52.7
PHP Version: 8.2.3
Composer Version: 2.5.4
Statamic version:  4.6.0 PRO
mitydigital/iconamic: 1.1.4
```

### Additional details

<img width="885" alt="SCR-20230613-pcyp" src="https://github.com/mitydigital/statamic-iconamic/assets/5454390/851c0cdb-cd7e-4f55-9db9-9dfe65628caf">
<img width="930" alt="SCR-20230613-pmye" src="https://github.com/mitydigital/statamic-iconamic/assets/5454390/0a871c08-5b15-4efa-83cc-6924afa455be">
