### ISSUE TITLE
The preview of the selected icon disappears

### ISSUE THREAD

**Issue by laracwi** [mitydigital/statamic-iconamic#5]
### Bug description

As soon as I select an icon via the iconamic field and save my changes, leave the Pages Collection and open it again, the selected icon is no longer visible (preview is gone).
<img width="408" alt="Bildschirmfoto 2023-06-14 um 14 11 43" src="https://github.com/mitydigital/statamic-iconamic/assets/78366637/37a28239-afaa-428b-a498-68b0baa38726">

### Steps to reproduce

1. add the iconamic field to fieldset
2. use the fieldset in pages collection
3. choose icon inside fieldset
4. save changes
5. leave the pages collection 
6. enter the pages collection again
7.  icon preview inside fieldset is gone 

### Environment and versions

```yaml
Statamic
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.6.0 PRO

Statamic Addons
mitydigital/iconamic: 1.1.5
```
