### ISSUE TITLE
Picking Icon with iconamic tag needs a path set

### ISSUE THREAD

**Issue by lukas-staab** [mitydigital/statamic-iconamic#6]
### Bug description

I have installed Fontawesome via `npm install --save @fortawesome/fontawesome-free`

My config/iconamic.php file looks like: 
```
'path' => 'node_modules/@fortawesome/fontawesome-free/svgs',
'path_helper' => 'base_path',
'recursive' => true,
```
Inline documentation suggested you can overwrite the path per usage, which implied to me I have not to set it everytime. But
```
{{ iconamic icon="solid/check" }}
```
does not work, while
```
{{ iconamic icon="solid/check" path="node_modules/@fortawesome/fontawesome-free/svgs" }} 
```
does. If there is a better way to achieve what I want, i am open to suggestions.  

### Steps to reproduce

See above.

### Environment and versions

```yaml
Environment
Application Name: Statamic
Laravel Version: 11.9.2
PHP Version: 8.3.7
Composer Version: 2.7.6
Environment: local
Debug Mode: ENABLED
URL: localhost:8000
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 1
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.7.2 PRO

Statamic Addons
mitydigital/iconamic: 2.1.0
```
